version: '3.7'

services:
  yta_db:
    image: mysql:8.0
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app_network
    volumes:
      - yta_mysql_data:/var/lib/mysql

  yta_minio:
    image: quay.io/minio/minio:RELEASE.2023-02-22T18-23-45Z
    command: server --console-address ":9090"
    ports:
      - "${MINIO_SERVER_PORT}:9000"
      - 9090:9090
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_SERVER_PORT}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    # hostname: ${MINIO_HOSTNAME}
    networks:
      - app_network
    volumes:
      - yta_minio_data:/mnt/data

  yta_api:
    build: .
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - yta_db
    networks:
      - app_network

volumes:
  yta_mysql_data:
    driver: local
  yta_minio_data:

networks:
  app_network:
    driver: bridge
